services:
  rasa:
    build:
      context: .
      dockerfile: Dockerfile.rasa.ubuntu
    volumes:
      - ./rasa:/rasa-home:r
      - ./rasa-cache:/app/.cache:rw
    ports:
      - 5005:5005
    command: run --debug --enable-api -p 5005 -m /rasa-home/models --cors "*"
    user: "${UID}:${GID}"
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
      args:
        - RASA_URL=http://localhost:5005
    ports:
      - 8080:80
