language: ru

pipeline:
- name: JiebaTokenizer                        # Токенизация русского языка
- name: RegexFeaturizer                       # Регулярные выражения для извлечения особенностей
- name: LexicalSyntacticFeaturizer            # Лексический синтаксический анализ
- name: CountVectorsFeaturizer                # Векторизация токенов
- name: CountVectorsFeaturizer                # Векторизация символов
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4

- name: "HFTransformersNLP"                   # Использование предобученной модели BERT
  model_name: "DeepPavlov/rubert-base-cased"
  model_weights: "DeepPavlov/rubert-base-cased"
  cache_dir: null

- name: DIETClassifier                        # Классификатор интентов и сущностей
  epochs: 100
  transformer_size: 256
  number_of_transformer_layers: 2
  use_masked_language_model: true
  batch_strategy: "balanced"
  hidden_layers_sizes:
    text: [256, 128]

- name: EntitySynonymMapper                   # Сопоставление синонимов сущностей
- name: ResponseSelector                      # Модель для выбора ответа
  epochs: 100
assistant_id: 20240918-162154-chewy-negation
